### ISSUE TITLE
Error if file is read-only(?)

### ISSUE THREAD

**Issue by tammojan** [aroffringa/dysco#5]
I have only read-only access to a MS, which in principle should be enough (I don't need to write anything). Doing a simple taql query results in `Table DataManager error: I/O error: could not write to file -- Error occured inside the Dysco Storage Manager`.

Does dysco always need write access to the files?

For reference, the taql command was `select from bla.MS`, stack trace:
```
#0  0x00007ffff6070c10 in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00007ffff551922d in dyscostman::DyscoStMan::open (
    this=0x6f2c20, nRow=<optimized out>)
    at /home/dijkema/opt/dysco/src/dyscostman.cpp:290
#2  0x00007ffff7808d87 in casa::DataManager::open1 (this=0x6f2c20,
    nrrow=6798145, ios=...)
    at /home/dijkema/opt/casacore/src/tables/DataMan/DataManager.cc:97
#3  0x00007ffff7743d42 in casa::ColumnSet::getFile (this=0x6ea900,
    ios=..., tab=..., nrrow=6798145, bigEndian=false, tsmOption=...)
    at /home/dijkema/opt/casacore/src/tables/Tables/ColumnSet.cc:899
#4  0x00007ffff7760059 in casa::PlainTable::PlainTable (
    this=0x68b4b0, version=2, tabname=..., type=..., nrrow=6798145,
    opt=1, lockOptions=..., tsmOption=..., addToCache=true, locknr=0)
    at /home/dijkema/opt/casacore/src/tables/Tables/PlainTable.cc:240
#5  0x00007ffff77aa261 in casa::Table::makeBaseTable (name=...,
    type=..., tableOption=1, lockOptions=..., tsmOpt=...,
    addToCache=true, locknr=0)
    at /home/dijkema/opt/casacore/src/tables/Tables/Table.cc:558
#6  0x00007ffff77a9f5a in casa::Table::open (this=0x7fffffffcc60,
    name=..., type=..., tableOption=1, lockOptions=..., tsmOpt=...)
    at /home/dijkema/opt/casacore/src/tables/Tables/Table.cc:528
#7  0x00007ffff77a792f in casa::Table::Table (this=0x7fffffffcc60,
    name=..., lockOptions=..., option=casa::Table::Old, tsmOpt=...)
    at /home/dijkema/opt/casacore/src/tables/Tables/Table.cc:91
#8  0x00007ffff77a86f1 in casa::Table::openTable (tableName=...,
    lockOptions=..., option=casa::Table::Old, tsmOption=...)
    at /home/dijkema/opt/casacore/src/tables/Tables/Table.cc:294
#9  0x00007ffff77a8676 in casa::Table::openTable (tableName=...,
    option=casa::Table::Old, tsmOption=...)
    at /home/dijkema/opt/casacore/src/tables/Tables/Table.cc:284
#10 0x00007ffff79ec722 in casa::TableParseSelect::makeTable (
    this=0x688d80, tabnr=-1, name=..., ftab=..., shorthand=...,
    tempTables=std::vector of length 0, capacity 0,
    stack=std::vector of length 1, capacity 1 = {...},
    alwaysOpen=true)
    at /home/dijkema/opt/casacore/src/tables/TaQL/TableParse.cc:301
#11 0x00007ffff79ec310 in casa::TableParseSelect::addTable (
    this=0x688d80, tabnr=-1, name=..., ftab=..., shorthand=...,
    tempTables=std::vector of length 0, capacity 0,
    stack=std::vector of length 1, capacity 1 = {...})
    at /home/dijkema/opt/casacore/src/tables/TaQL/TableParse.cc:252
#12 0x00007ffff79cd087 in casa::TaQLNodeHandler::handleTables (
    this=0x7fffffffd060, node=...)
    at /home/dijkema/opt/casacore/src/tables/TaQL/TaQLNodeHandler.cc:904
#13 0x00007ffff79c9fc1 in casa::TaQLNodeHandler::visitSelectNode (
    this=0x7fffffffd060, node=...)
    at /home/dijkema/opt/casacore/src/tables/TaQL/TaQLNodeHandler.cc:51---Type <return> to continue, or q <return> to quit---
5
#14 0x00007ffff79c1eaf in casa::TaQLSelectNodeRep::visit (
    this=0x688cc0, visitor=...)
    at /home/dijkema/opt/casacore/src/tables/TaQL/TaQLNodeDer.cc:1170
#15 0x00007ffff79cec33 in casa::TaQLNode::visit (this=0x7fffffffd1c0,
    visitor=...)
    at /home/dijkema/opt/casacore/src/casacore/tables/TaQL/TaQLNode.h:132
#16 0x00007ffff79c677a in casa::TaQLNodeHandler::handleTree (
    this=0x7fffffffd060, node=...,
    tempTables=std::vector of length 0, capacity 0)
    at /home/dijkema/opt/casacore/src/tables/TaQL/TaQLNodeHandler.cc:59
#17 0x00007ffff7a0488e in casa::tableCommand (str=...,
    tempTables=std::vector of length 0, capacity 0, cols=...,
    commandType=...)
    at /home/dijkema/opt/casacore/src/tables/TaQL/TableParse.cc:4054
#18 0x000000000043b34e in doCommand (printCommand=false,
    printSelect=true, printMeas=true, printRows=true,
    printHeader=true, delim=..., varName=..., prefix=..., str=...,
    tempTables=std::vector of length 0, capacity 0)
    at /home/dijkema/opt/casacore/src/tables/apps/taql.cc:624
#19 0x000000000043e02d in main (argc=2, argv=0x7fffffffd778)
    at /home/dijkema/opt/casacore/src/tables/apps/taql.cc:1081
```

**Comment by aroffringa** [comment]
I never tested read only access, so it indeed probably doesn't work, but should be easy to fix. Thanks for reporting!

**Comment by aroffringa** [comment]
I've committed changes to fix this. I added a test case that opens a RO set, that indeed initially failed, but now no longer.
